services:
  proxy:
    depends_on:
      - frontend
      - backend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  backend:
    build:
      dockerfile: Dockerfile
      context: ./api
    expose:
      - "5000"

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./sys-stats
    expose:
      - "3000"

